# Experiment goal: Train a Qwen model with no-duplicate hybrid training dataset, as control group. 20k samples in total.
# 1. Model: Qwen-2.5-7B-Instruct
# 2. Training Mode: sft
# 3. Dataset: A hybrid dataset, 20k samples in total, without no positive negative sample pairs. (/think : /No_think = 56 : 44)
# 4. System prompt: empty string


### model
# NOTE:----------Double check this one!----------
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
# image_max_pixels: 262144
# video_max_pixels: 16384
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# NOTE:----------Double check this one!----------
dataset: no_duplicate_20k
# NOTE:----------Double check this one!----------
template: qwen25
cutoff_len: 16384
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
# NOTE:----------Double check this one!----------
default_system: ""



### output
# NOTE:----------Double check this one!----------
output_dir: saves/ht_no_duplicate/Qwen_no_duplicate_20k
save_only_model: true 
logging_steps: 1
# NOTE:----------Double check this one!----------
save_steps: 4000
plot_loss: true
overwrite_output_dir: false
# save_only_model: false
# NOTE:----------Double check this one!----------
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]
# NOTE:----------Double check this one!----------
run_name: Qwen_no_duplicate_20k

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# flash_attn: fa2


### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
