### model
model_name_or_path: <your_model_path>
# image_max_pixels: 262144
# video_max_pixels: 16384
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: hybrid_thinking_demo_phase2
template: qwen25
cutoff_len: 16384
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
default_system: ""


### output
output_dir: saves/ht_2phases/Qwen2.5-7B_phase2_directly
save_only_model: true 
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: false
# save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: HT_Qwen2.5-7B_phase2_directly

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# flash_attn: fa2


### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
