# Experiment goal and design
# Experiment goal: Train a Llama model with full mixed 2 phases training dataset, as control group. 140k samples in total.
# Design & Settings:
# 1. Model: Llama-3-8B-Instruct
# 2. Training Mode: Vanilla training, using mixed 2 phases dataset.
# 3. Dataset: A full mixed 2 phases training dataset, as control group. 140k samples in total.
# 4. System prompt: empty string


### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
# image_max_pixels: 262144
# video_max_pixels: 16384
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: naive-mix_140k
template: llama3
cutoff_len: 16384
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
default_system: ""


### output
output_dir: saves/naive-mix/Llama3_naive-mix_140k
save_only_model: true 
logging_steps: 1
save_steps: 5000
plot_loss: true
overwrite_output_dir: false
# save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: naive-mix_Llama3_140k

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# flash_attn: fa2


### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
