### model
model_name_or_path: /media/srw/data/LLMs/Qwen/Qwen2.5-0.5B
# image_max_pixels: 262144
# video_max_pixels: 16384
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: hybrid_thinking_demo_phase1
template: qwen25
cutoff_len: 2048
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
default_system: ""


### output
output_dir: /media/srw/data/LLMs_training/Qwen2.5-0.5B_phase1
save_only_model: true 
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: false
# save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: local_ht_qwen2_0.5b_phase1

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
flash_attn: fa2


### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
